Feature/persist fta diagram layout
kbss-cvut/fta-fmea-ui pull request #140
Opened 2024-01-05 09:34 UTC by kostobog

Partially implements #131.
Server side related changes:
- kbss-cvut/fta-fmea#54

2024-01-09 16:10 UTC, blcham requested changes
see my comments about @ts-ignore

2024-01-12 23:07 UTC, blcham commented
@kostobog

2024-01-16 13:46 UTC, kostobog commented on src/components/editor/faultTree/shapes/RenderTree.tsx
> +        // @ts-ignore
Yes, without it I get a compilation error.

2024-01-16 14:00 UTC, kostobog commented on src/components/editor/faultTree/Editor.tsx
> +        // @ts-ignore
In Editor, the @ts-ignore is used when working with `_localContext`. I resolved this by encapsulating access to `_localContext` in getters and refactored the rest of the annotated lines.

I also removed other @ts-ignore which did not cause a compilation error.

2024-01-16 14:03 UTC, merged