Added side table for cutsets
kbss-cvut/fta-fmea-ui pull request #218
Opened 2024-03-22 17:41 UTC by Kasmadei

2024-03-26 19:01 UTC, blcham requested changes
See my comments.

2024-03-26 19:01 UTC, blcham commented on src/components/editor/faultTree/menu/FaultEventScenariosTable.tsx
> +              <TableCell>Probability</TableCell>
missing i18n

2024-03-27 17:47 UTC, Kasmadei commented on src/components/editor/faultTree/menu/FaultEventScenariosTable.tsx
> +  }
Changed (created sep. function for this)

2024-03-27 17:48 UTC, Kasmadei commented on src/components/editor/faultTree/Editor.tsx
> +        const result = getScenariosWithHighestProbability(faultTree.faultEventScenarios);
Right, i have changed it already in next PR

2024-03-27 18:23 UTC, Kasmadei commented on src/components/editor/faultTree/menu/FaultEventScenariosTable.tsx
> +              <TableCell>Probability</TableCell>
Fixed

2024-03-27 19:09 UTC, blcham commented on src/components/editor/faultTree/menu/FaultEventScenariosTable.tsx
> +import { asArray } from "@utils/treeUtils";
Although it is confusing that it belongs to treeUtils as it does not have anything to do with trees, but it is acceptable to me like that. I would rather add it to a new class called CollectionsUtils, ArrayUtils or just Utils.

2024-03-27 20:09 UTC, merged