Feature/hint component
kbss-cvut/fta-fmea-ui pull request #228
Opened 2024-04-02 19:01 UTC by Kasmadei

Resolves: https://github.com/kbss-cvut/fta-fmea-ui/issues/227
<img width="384" alt="Screenshot 2024-04-02 at 8 37 14 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/8cc027a5-3f03-446c-aec4-48c3426e07d2">
<img width="407" alt="Screenshot 2024-04-02 at 8 37 20 PM" src="https://github.com/kbss-cvut/fta-fmea-ui/assets/49252228/7f578650-59f2-4c80-9893-bae273663cf5">

Please, check the translation @blcham

2024-04-03 14:34 UTC, grotskat commented
Intenzita poruch založená na FHA
Intenzita poruch vypočtená na základě počtu výskytů vrcholových událostí během provozu letadla pro každý typ letadla zvlášť.

2024-04-03 18:39 UTC, Kasmadei commented
Updated and ready

2024-04-03 20:44 UTC, grotskat requested changes

2024-04-03 20:44 UTC, grotskat commented on public/locales/cs/translation.json
> +      "description": "Míra selhání ručně nastavená týmem AVA na základě zkušeností a inženýrského posouzení."
Manuálně definovaná intenzita poruch
Intenzita poruch nastavená manuálně týmem AVA na základě zkušeného inženýrského úsudku.

2024-04-03 20:44 UTC, grotskat commented on public/locales/cs/translation.json
> +      "description": "Míra selhání spočítaná na základě počtu výskytů selhání komponent během provozu letadla napříč všemi typy letadel. Každá konkrétní komponenta má definované jedinečné číslo SNS."
Provozní intenzita poruch
Intenzita poruch vypočtená na základě počtu výskytů selhání komponenty během provozu letadla napříč všemi typy letadel. Každá specifická komponenta má definované jedinečné číslo SNS.

2024-04-03 20:44 UTC, grotskat commented on public/locales/cs/translation.json
> +      "description": "Míra selhání předpovězená dodavatelem nebo AVA během návrhové fáze, která je součástí vstupního tabulkového listu SNS pro každý typ letadla."
Predikovaná intenzita poruch
Intenzita poruch predikovaná dodavatelem nebo AVA během fáze návrhu, která je součástí vstupní tabulky SNS pro každý typ letadla.

2024-04-03 20:44 UTC, grotskat commented on public/locales/cs/translation.json
> +      "description": "Požadovaná míra selhání na základě závažnosti hlavní události podle MIL-STD-882."
Požadovaná intenzita poruch
Regulatorní požadavek na intenzitu poruch na základě závažnosti vrcholové události podle MIL-STD-882.

2024-04-03 20:44 UTC, grotskat commented on public/locales/cs/translation.json
> +      "description": "Míra selhání vypočtená uvnitř zobrazeného FTA na základě základních událostí a propojovacích bran."
Vypočtená intenzita poruch
Intenzita poruch vypočtená v rámci zobrazeného FTA na základě základních událostí a propojovacích logických hradel.

2024-04-04 12:14 UTC, blcham commented on public/locales/cs/translation.json
> +      "description": "Intenzita poruch vypočtená na základě počtu výskytů vrcholových událostí během provozu letadla pro každý typ letadla zvlášť."
```suggestion
      "description": "Intenzita poruch vypočtená v rámci zobrazeného FTA na základě základních událostí a propojovacích logických hradel."
```

2024-04-04 12:14 UTC, blcham commented on public/locales/cs/translation.json
> +      "description": "Míra selhání vypočtená uvnitř zobrazeného FTA na základě základních událostí a propojovacích bran."
done as suggestions.

2024-04-04 12:48 UTC, grotskat commented on public/locales/cs/translation.json
> +      "title": "Vypočítaná míra selhání",
```suggestion
      "title": "Vypočtená intenzita poruch",
```

2024-04-04 13:28 UTC, blcham requested changes
See my comment.

BTW, i18n is solved, see last comment.

2024-04-04 13:28 UTC, blcham commented on src/services/faultTreeService.tsx
> +    const upperBound = response.data?.manifestingEvent?.supertypes?.[0]?.failureRate?.requirement?.upperBound;
We have a standard way that is used everywhere how to:
1) retrieve data from the server
2) shape the data according to our needs

What is the motivation for not only returning the `result` but also the `reqProb` here? In this way, we will not have a single source of data as we would be able to access some value using different paths:
- `rootReqProb`
-  `ftaTree?.manifestingEvent?.supertypes?.[0]?.failureRate?.requirement?.upperBound`

Is there any advantage of polluting this code in such a way? How about using `ftaTree?.manifestingEvent?.supertypes?.[0]?.failureRate?.requirement?.upperBound` directly in useEffect(() method instead? Does it have a drawback?

2024-04-04 13:29 UTC, blcham commented on src/services/faultTreeService.tsx
> +    const upperBound = response.data?.manifestingEvent?.supertypes?.[0]?.failureRate?.requirement?.upperBound;
Maybe you can even define `reqProb = ftaTree?.manifestingEvent?.supertypes?.[0]?.failureRate?.requirement?.upperBound` before entering `useEffect()`

2024-04-11 16:41 UTC, blcham approved these changes

2024-04-11 16:42 UTC, merged