Add oidc authentication
kbss-cvut/fta-fmea-ui pull request #260
Opened 2024-04-29 15:26 UTC by LaChope

Resolves #126. It mainly uses the same implementation as the [record-manager-ui](https://github.com/kbss-cvut/record-manager-ui).

I would not merge before the backend is also implemented to test it first.

2024-04-30 05:29 UTC, blcham requested changes
see my comments

2024-04-30 05:29 UTC, blcham commented on deploy/keycloak-auth/docker-compose.yml
> +      VOCABULARY_USER_TYPE: "http://onto.fel.cvut.cz/ontologies/record-manager/user"
This might be an issue, we might need to align urls.

2024-04-30 05:29 UTC, blcham commented on deploy/keycloak-auth/.env
> +RECORD_SET_NAME=ff-iauth-demo
```suggestion
RECORD_SET_NAME=ff-kauth-demo
```

2024-04-30 05:29 UTC, blcham commented on src/utils/constants.tsx
> +  DOCTOR: "Regular User",
???

2024-05-03 09:06 UTC, merged

2024-05-03 09:06 UTC, LaChope commented
@blcham This PR was rebased