Create FTA algorithm description
kbss-cvut/fta-fmea-ui pull request #36
Opened 2022-03-16 15:13 UTC by blcham

@Matthew-Kulich @kostobog @ahmadjana 
- please check the linking to main readme 
- do both examples make sense ?

2022-03-16 16:21 UTC, Matthew-Kulich requested changes
LGTM

2022-03-16 16:21 UTC, Matthew-Kulich commented on doc/fta-construction-algorithm.md
> +modeling constructs used to describe system behaviors. The algorithm implemented in this tool is described by recursive function GENERATE_FTA which represents inner nodes of FTA tree as fault events.
```suggestion
modeling constructs used to describe system behaviors. The algorithm implemented in this tool is described by recursive function GENERATE_FTA which represents root node and some inner nodes of FTA tree as fault events. Each node that is represented by fault event is attached to OR gate or AND
```

2022-03-16 16:26 UTC, merged

2022-03-16 16:27 UTC, blcham commented
@kostobog https://github.com/ahmadjana please have a look and comment even it is merged

2022-03-17 22:35 UTC, ahmadjana commented
the readme is OK. But we shouldn't explain the examples

2022-03-17 23:49 UTC, blcham commented
> the readme is OK. But we shouldn't explain the examples

?