Add operational hours
kbss-cvut/fta-fmea-ui pull request #405
Opened 2024-06-12 10:23 UTC by LaChope

Resolves #403

2024-06-14 13:54 UTC, LaChope commented
@blcham just FYI, no need to review now, it is still WIP

2024-06-17 13:14 UTC, blcham requested changes
There is only one issue related to you code directly, other issues i will try to target as separate issues.

2024-06-17 13:14 UTC, blcham commented on src/utils/utils.tsx
> +export const getModifiedFaultTreesList = (faultTrees: FaultTree[], selected: System) => {
We have getModifiedSystemsList and getModifiedFaultTreesList (CC @Kasmadei ): 
-- basically the same name without any comment on what it does, but they do fundamentally different things :(. This is confusing and can lead to errors easily.
-- getModifiedSystemsList -- reorders elements based on selected one
-- getModifiedFaultTreesList -- filter elements based on an attribute

2024-06-17 13:14 UTC, blcham commented on src/components/dashboard/content/list/SystemOverview.tsx
> +        <FaultTreeAndSystemOverviewTable systems={systems} handleSystemContextMenu={handleContextMenu} />
I will create ticket for that.

2024-06-17 13:14 UTC, blcham commented on src/utils/utils.tsx
> +export const getModifiedFaultTreesList = (faultTrees: FaultTree[], selected: System) => {
I will create ticket for that.

2024-06-17 14:50 UTC, LaChope commented on src/components/editor/faultTree/canvas/EditorCanvas.tsx
> +      setInputColor("red");
@blcham I refactored adding `synchronized` and `notSynchronized` directly in the theme

2024-06-17 14:51 UTC, LaChope commented on public/locales/cs/translation.json
> +    "operationalHours": "Provozní Doba"
@grotskat Can you revise this?

2024-06-18 12:15 UTC, blcham commented on src/components/editor/faultTree/canvas/EditorCanvas.tsx
> +      setInputColor("red");
ok

2024-06-18 12:37 UTC, blcham commented on src/utils/utils.tsx
> +export const getModifiedFaultTreesList = (faultTrees: FaultTree[], selected: System) => {
Will be resolved in https://github.com/kbss-cvut/fta-fmea-ui/pull/422

2024-06-18 12:39 UTC, grotskat submitted a review, later dismissed

2024-06-18 12:39 UTC, grotskat commented on public/locales/cs/translation.json
> +    "operationalHours": "Provozní Doba"
```suggestion
    "operationalHours": "Doba provozu"
```

2024-06-18 12:42 UTC, blcham commented
@LaChope does it make sense to you to improve the git history by squashing some of the commits to together

2024-06-18 12:45 UTC, blcham commented on src/components/dashboard/content/list/SystemOverview.tsx
> +        <FaultTreeAndSystemOverviewTable systems={systems} handleSystemContextMenu={handleContextMenu} />
Will be resolved by https://github.com/kbss-cvut/fta-fmea-ui/issues/423

2024-06-18 12:47 UTC, blcham approved these changes
LGTM

@LaChope does it make sense to you to improve the git history by squashing some of the commits to together + do not forget to rebase

2024-06-18 13:12 UTC, LaChope commented
> LGTM
> 
> @LaChope does it make sense to you to improve the git history by squashing some of the commits to together + do not forget to rebase

@blcham it would make sense to do it, but is it possible to squash when it was already pushed? Or I have to use --force, right?

2024-06-18 13:17 UTC, blcham commented
@LaChope  you have to do force in this case

2024-06-18 15:16 UTC, merged

2024-06-18 15:18 UTC, LaChope commented
@blcham I did squash but not so many commits in the end, I think history might be useful for later.

2024-06-18 22:32 UTC, blcham commented
OK, although I thought you would squash the last commit.

2024-06-19 12:13 UTC, LaChope commented
Will do next time, using interactive rebase rather than squash feature.