483 - Unsaved changes modal
kbss-cvut/fta-fmea-ui pull request #530
Opened 2024-07-17 13:18 UTC by Kasmadei

Point for: https://github.com/kbss-cvut/fta-fmea-ui/issues/483
(if FTA is deselected user is notified by a modal and can SAVE/DISCARD changes)
Has eng/cz text.
<img width="771" alt="Screenshot 2024-07-17 at 3 18 33 PM" src="https://github.com/user-attachments/assets/f397df3a-6ed8-44e3-aa1f-1f1a122e10c6">

2024-07-17 14:15 UTC, blcham requested changes

2024-07-17 14:15 UTC, blcham commented on src/components/editor/faultTree/canvas/EditorCanvas.tsx
> +            newShapeToolData={sidebarSelectedEvent}
Why newShapeToolData ?

2024-07-17 14:54 UTC, blcham commented
We are still not showing modal for:
- diagram options 
- back button

2024-07-17 15:06 UTC, blcham commented on src/components/editor/faultTree/canvas/EditorCanvas.tsx
> +            newShapeToolData={sidebarSelectedEvent}
selectedShapeToolData

2024-07-18 05:33 UTC, blcham commented
@LaChope please have a look so you know what is @Kasmadei implementing

2024-07-18 07:15 UTC, LaChope approved these changes
Looks good to me, LGTM after requested changes by @blcham were implemented.

2024-07-21 19:01 UTC, merged