Fix/small UI fixes
kbss-cvut/fta-fmea-ui pull request #553
Opened 2024-08-15 09:40 UTC by kostobog

@blcham 
Fixes #551 and #552

2024-08-15 14:57 UTC, blcham requested changes

2024-08-16 07:43 UTC, kostobog commented on src/components/dashboard/content/list/FaultTreeOverview.tsx
> +        renameTooltip={canRename ? "change fault tree title" : "FHA-based fault trees cannot be renamed."}
@kostobog 
done

2024-08-16 07:43 UTC, kostobog commented on src/components/dashboard/content/list/FaultTreeOverview.tsx
> +        renameTooltip={canRename ? "change fault tree title" : "FHA-based fault trees cannot be renamed."}
@blcham 
done

2024-08-16 10:09 UTC, blcham approved these changes

2024-08-16 10:09 UTC, blcham commented on public/locales/cs/translation.json
> +    "renameDisabledHint": "Stromy poruch založené na FHA nelze přejmenovat",
```suggestion
    "renameDisabledHint": "Stromy poruch založené na FHA nelze přejmenovat.",
```

2024-08-16 10:10 UTC, merged